### ISSUE TITLE
Feature Request - Hyper Backup

### ISSUE THREAD

**Issue by FerronN** [mib1185/py-synologydsm-api#345]
Hi,

I'm using Home Assistant and it uses this Python package if I'm correct. It works great so thank you for building and maintaining.
I've no Python knowledge and experience unfortunately, otherwise I would come up with a pull request.

Could you add support for the Hyper Backup? It would be great to list tasks and the result.
So you can monitor the status of the backup jobs. Maybe this package can be used as inspiration for this https://github.com/N4S4/synology-api?

Would you consider adding this feature?

**Comment by mib1185** [comment]
There is already an #234 open to add hyper backup support, further there was already a try from my side in #31 which unfortunately went stale. It is not as easy since Synology does not provide documentation about the hyper backup api

**Comment by FerronN** [comment]
Thanks for the reply. Then I will close this one if there are already two existing issues.
